# Generated by Django 4.0.3 on 2022-03-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Interaction time start')),
                ('date_end', models.DateTimeField(verbose_name='Interaction time end')),
                ('remote_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('is_denise', models.BooleanField(verbose_name='Message is from Denise')),
                ('text', models.TextField()),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.interaction')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
