# Generated by Django 4.0.3 on 2022-03-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_interaction_message_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interaction',
            new_name='Interactionz',
        ),
    ]
