# Generated by Django 4.0.3 on 2022-03-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_interaction_interactionz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interactionz',
            new_name='Interaction',
        ),
    ]
