# syntax=docker/dockerfile:1
FROM python:3.8-buster
WORKDIR /usr/denise/
COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
# install nginx
RUN apt update -y
RUN apt install -y nginx
RUN cp ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["sh", "-c", "nginx ; gunicorn denise.wsgi"]